
  version: smartide/v0.2
  orchestrator:
    type: docker-compose
    version: 3
  workspace:
    dev-container:
      service-name: boathouse-frontend-dev
      webide-port: 6800
      ide-type: vscode
      volumes: 
        git-config: true
        ssh-key: true
    services:  
      boathouse-frontend-dev:
        container_name: boathouse-frontend-dev
        image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-opvscode:latest
        restart: always
        environment:
          ROOT_PASSWORD: root123
        volumes:
          - .:/home/project
        expose:
          - 8080
          - 8081
        ports:
          - 8080:8080
          - 8081:8081
        networks:
          - boathouse-dev-network  
    networks:
      boathouse-dev-network:
        external: true
