
  version: smartide/v0.2
  orchestrator:
    type: docker-compose
    version: 3
  workspace:
    dev-container:
      service-name: boathouse-frontend
      webide-port: 6800
      ide-type: vscode  #vscode/theia
      volumes: 
        git-config: true
        ssh-key: true
    services:
  
      boathouse-frontend:
        image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-opvscode:latest
        restart: always
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
          ROOT_PASSWORD: root123
        volumes:
          - .:/home/project
        expose:
          - 8080
        ports:
          - 8080:8080
        networks:
          - smartide-network
  
    networks:
      smartide-network:
        external: true