apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-stack-k8s.yml
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: result
  name: result
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    targetPort: 80
  selector:
    io.kompose.service: result
status:
  loadBalancer: {}
